# this is the build file for project 
# it is autogenerated by the xmake build system.
# do not edit by hand.

CCACHE=/usr/bin/ccache
MM=/usr/bin/gcc
CC=/usr/bin/gcc
CXX=/usr/bin/gcc
AS=/usr/bin/gcc
MXX=/usr/bin/gcc

SH=/usr/bin/g++
AR=/usr/bin/ar
LD=/usr/bin/g++

webserver_CXXFLAGS=-m64 -g -O0 -Iinc -ISnowTcpLib -IwebServer
webserver_LDFLAGS=-m64 -L/usr/lib/x86_64-linux-gnu -L. -Wl,-rpath=$ORIGIN -lmysqlclient -lSnowTcpLib
SnowTcpLib_CXXFLAGS=-m64 -fPIC -g -O0 -Iinc -ISnowTcpLib -IwebServer
SnowTcpLib_SHFLAGS=-shared -fPIC -m64 -lpthread

default:  webserver SnowTcpLib

all:  webserver SnowTcpLib

.PHONY: default all  webserver SnowTcpLib

webserver: ./webserver
./webserver: ./libSnowTcpLib.so build/.objs/webserver/linux/x86_64/debug/src/db.cc.o build/.objs/webserver/linux/x86_64/debug/src/WebService.cc.o build/.objs/webserver/linux/x86_64/debug/webServer/HttpConn.cc.o build/.objs/webserver/linux/x86_64/debug/webServer/webServer.cc.o build/.objs/webserver/linux/x86_64/debug/webServer/TimeWheel.cc.o
	@echo linking.debug webserver
	@mkdir -p .
	@$(LD) -o ./webserver build/.objs/webserver/linux/x86_64/debug/src/db.cc.o build/.objs/webserver/linux/x86_64/debug/src/WebService.cc.o build/.objs/webserver/linux/x86_64/debug/webServer/HttpConn.cc.o build/.objs/webserver/linux/x86_64/debug/webServer/webServer.cc.o build/.objs/webserver/linux/x86_64/debug/webServer/TimeWheel.cc.o $(webserver_LDFLAGS) > build/.build.log 2>&1

build/.objs/webserver/linux/x86_64/debug/src/db.cc.o: src/db.cc
	@echo ccache compiling.debug src/db.cc
	@mkdir -p build/.objs/webserver/linux/x86_64/debug/src
	@$(CCACHE) $(CXX) -c $(webserver_CXXFLAGS) -o build/.objs/webserver/linux/x86_64/debug/src/db.cc.o src/db.cc > build/.build.log 2>&1

build/.objs/webserver/linux/x86_64/debug/src/WebService.cc.o: src/WebService.cc
	@echo ccache compiling.debug src/WebService.cc
	@mkdir -p build/.objs/webserver/linux/x86_64/debug/src
	@$(CCACHE) $(CXX) -c $(webserver_CXXFLAGS) -o build/.objs/webserver/linux/x86_64/debug/src/WebService.cc.o src/WebService.cc > build/.build.log 2>&1

build/.objs/webserver/linux/x86_64/debug/webServer/HttpConn.cc.o: webServer/HttpConn.cc
	@echo ccache compiling.debug webServer/HttpConn.cc
	@mkdir -p build/.objs/webserver/linux/x86_64/debug/webServer
	@$(CCACHE) $(CXX) -c $(webserver_CXXFLAGS) -o build/.objs/webserver/linux/x86_64/debug/webServer/HttpConn.cc.o webServer/HttpConn.cc > build/.build.log 2>&1

build/.objs/webserver/linux/x86_64/debug/webServer/webServer.cc.o: webServer/webServer.cc
	@echo ccache compiling.debug webServer/webServer.cc
	@mkdir -p build/.objs/webserver/linux/x86_64/debug/webServer
	@$(CCACHE) $(CXX) -c $(webserver_CXXFLAGS) -o build/.objs/webserver/linux/x86_64/debug/webServer/webServer.cc.o webServer/webServer.cc > build/.build.log 2>&1

build/.objs/webserver/linux/x86_64/debug/webServer/TimeWheel.cc.o: webServer/TimeWheel.cc
	@echo ccache compiling.debug webServer/TimeWheel.cc
	@mkdir -p build/.objs/webserver/linux/x86_64/debug/webServer
	@$(CCACHE) $(CXX) -c $(webserver_CXXFLAGS) -o build/.objs/webserver/linux/x86_64/debug/webServer/TimeWheel.cc.o webServer/TimeWheel.cc > build/.build.log 2>&1

SnowTcpLib: ./libSnowTcpLib.so
./libSnowTcpLib.so: build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/Buffer.cc.o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/Channel.cc.o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/EventLoopThread.cc.o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/Socket.cc.o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/DefaultPoller.cc.o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/TimerQueue.cc.o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/Poller.cc.o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/CurrentThread.cc.o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/TcpServer.cc.o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/Timestamp.cc.o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/Logger.cc.o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/Acceptor.cc.o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/EventLoopThreadPool.cc.o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/TcpConnection.cc.o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/EPollPoller.cc.o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/EventLoop.cc.o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/InetAddress.cc.o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/Timer.cc.o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/Thread.cc.o
	@echo linking.debug libSnowTcpLib.so
	@mkdir -p .
	@$(SH) -o ./libSnowTcpLib.so build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/Buffer.cc.o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/Channel.cc.o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/EventLoopThread.cc.o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/Socket.cc.o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/DefaultPoller.cc.o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/TimerQueue.cc.o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/Poller.cc.o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/CurrentThread.cc.o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/TcpServer.cc.o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/Timestamp.cc.o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/Logger.cc.o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/Acceptor.cc.o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/EventLoopThreadPool.cc.o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/TcpConnection.cc.o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/EPollPoller.cc.o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/EventLoop.cc.o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/InetAddress.cc.o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/Timer.cc.o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/Thread.cc.o $(SnowTcpLib_SHFLAGS) > build/.build.log 2>&1

build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/Buffer.cc.o: SnowTcpLib/Buffer.cc
	@echo ccache compiling.debug SnowTcpLib/Buffer.cc
	@mkdir -p build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib
	@$(CCACHE) $(CXX) -c $(SnowTcpLib_CXXFLAGS) -o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/Buffer.cc.o SnowTcpLib/Buffer.cc > build/.build.log 2>&1

build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/Channel.cc.o: SnowTcpLib/Channel.cc
	@echo ccache compiling.debug SnowTcpLib/Channel.cc
	@mkdir -p build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib
	@$(CCACHE) $(CXX) -c $(SnowTcpLib_CXXFLAGS) -o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/Channel.cc.o SnowTcpLib/Channel.cc > build/.build.log 2>&1

build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/EventLoopThread.cc.o: SnowTcpLib/EventLoopThread.cc
	@echo ccache compiling.debug SnowTcpLib/EventLoopThread.cc
	@mkdir -p build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib
	@$(CCACHE) $(CXX) -c $(SnowTcpLib_CXXFLAGS) -o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/EventLoopThread.cc.o SnowTcpLib/EventLoopThread.cc > build/.build.log 2>&1

build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/Socket.cc.o: SnowTcpLib/Socket.cc
	@echo ccache compiling.debug SnowTcpLib/Socket.cc
	@mkdir -p build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib
	@$(CCACHE) $(CXX) -c $(SnowTcpLib_CXXFLAGS) -o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/Socket.cc.o SnowTcpLib/Socket.cc > build/.build.log 2>&1

build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/DefaultPoller.cc.o: SnowTcpLib/DefaultPoller.cc
	@echo ccache compiling.debug SnowTcpLib/DefaultPoller.cc
	@mkdir -p build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib
	@$(CCACHE) $(CXX) -c $(SnowTcpLib_CXXFLAGS) -o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/DefaultPoller.cc.o SnowTcpLib/DefaultPoller.cc > build/.build.log 2>&1

build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/TimerQueue.cc.o: SnowTcpLib/TimerQueue.cc
	@echo ccache compiling.debug SnowTcpLib/TimerQueue.cc
	@mkdir -p build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib
	@$(CCACHE) $(CXX) -c $(SnowTcpLib_CXXFLAGS) -o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/TimerQueue.cc.o SnowTcpLib/TimerQueue.cc > build/.build.log 2>&1

build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/Poller.cc.o: SnowTcpLib/Poller.cc
	@echo ccache compiling.debug SnowTcpLib/Poller.cc
	@mkdir -p build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib
	@$(CCACHE) $(CXX) -c $(SnowTcpLib_CXXFLAGS) -o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/Poller.cc.o SnowTcpLib/Poller.cc > build/.build.log 2>&1

build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/CurrentThread.cc.o: SnowTcpLib/CurrentThread.cc
	@echo ccache compiling.debug SnowTcpLib/CurrentThread.cc
	@mkdir -p build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib
	@$(CCACHE) $(CXX) -c $(SnowTcpLib_CXXFLAGS) -o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/CurrentThread.cc.o SnowTcpLib/CurrentThread.cc > build/.build.log 2>&1

build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/TcpServer.cc.o: SnowTcpLib/TcpServer.cc
	@echo ccache compiling.debug SnowTcpLib/TcpServer.cc
	@mkdir -p build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib
	@$(CCACHE) $(CXX) -c $(SnowTcpLib_CXXFLAGS) -o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/TcpServer.cc.o SnowTcpLib/TcpServer.cc > build/.build.log 2>&1

build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/Timestamp.cc.o: SnowTcpLib/Timestamp.cc
	@echo ccache compiling.debug SnowTcpLib/Timestamp.cc
	@mkdir -p build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib
	@$(CCACHE) $(CXX) -c $(SnowTcpLib_CXXFLAGS) -o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/Timestamp.cc.o SnowTcpLib/Timestamp.cc > build/.build.log 2>&1

build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/Logger.cc.o: SnowTcpLib/Logger.cc
	@echo ccache compiling.debug SnowTcpLib/Logger.cc
	@mkdir -p build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib
	@$(CCACHE) $(CXX) -c $(SnowTcpLib_CXXFLAGS) -o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/Logger.cc.o SnowTcpLib/Logger.cc > build/.build.log 2>&1

build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/Acceptor.cc.o: SnowTcpLib/Acceptor.cc
	@echo ccache compiling.debug SnowTcpLib/Acceptor.cc
	@mkdir -p build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib
	@$(CCACHE) $(CXX) -c $(SnowTcpLib_CXXFLAGS) -o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/Acceptor.cc.o SnowTcpLib/Acceptor.cc > build/.build.log 2>&1

build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/EventLoopThreadPool.cc.o: SnowTcpLib/EventLoopThreadPool.cc
	@echo ccache compiling.debug SnowTcpLib/EventLoopThreadPool.cc
	@mkdir -p build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib
	@$(CCACHE) $(CXX) -c $(SnowTcpLib_CXXFLAGS) -o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/EventLoopThreadPool.cc.o SnowTcpLib/EventLoopThreadPool.cc > build/.build.log 2>&1

build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/TcpConnection.cc.o: SnowTcpLib/TcpConnection.cc
	@echo ccache compiling.debug SnowTcpLib/TcpConnection.cc
	@mkdir -p build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib
	@$(CCACHE) $(CXX) -c $(SnowTcpLib_CXXFLAGS) -o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/TcpConnection.cc.o SnowTcpLib/TcpConnection.cc > build/.build.log 2>&1

build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/EPollPoller.cc.o: SnowTcpLib/EPollPoller.cc
	@echo ccache compiling.debug SnowTcpLib/EPollPoller.cc
	@mkdir -p build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib
	@$(CCACHE) $(CXX) -c $(SnowTcpLib_CXXFLAGS) -o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/EPollPoller.cc.o SnowTcpLib/EPollPoller.cc > build/.build.log 2>&1

build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/EventLoop.cc.o: SnowTcpLib/EventLoop.cc
	@echo ccache compiling.debug SnowTcpLib/EventLoop.cc
	@mkdir -p build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib
	@$(CCACHE) $(CXX) -c $(SnowTcpLib_CXXFLAGS) -o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/EventLoop.cc.o SnowTcpLib/EventLoop.cc > build/.build.log 2>&1

build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/InetAddress.cc.o: SnowTcpLib/InetAddress.cc
	@echo ccache compiling.debug SnowTcpLib/InetAddress.cc
	@mkdir -p build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib
	@$(CCACHE) $(CXX) -c $(SnowTcpLib_CXXFLAGS) -o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/InetAddress.cc.o SnowTcpLib/InetAddress.cc > build/.build.log 2>&1

build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/Timer.cc.o: SnowTcpLib/Timer.cc
	@echo ccache compiling.debug SnowTcpLib/Timer.cc
	@mkdir -p build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib
	@$(CCACHE) $(CXX) -c $(SnowTcpLib_CXXFLAGS) -o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/Timer.cc.o SnowTcpLib/Timer.cc > build/.build.log 2>&1

build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/Thread.cc.o: SnowTcpLib/Thread.cc
	@echo ccache compiling.debug SnowTcpLib/Thread.cc
	@mkdir -p build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib
	@$(CCACHE) $(CXX) -c $(SnowTcpLib_CXXFLAGS) -o build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/Thread.cc.o SnowTcpLib/Thread.cc > build/.build.log 2>&1

clean:  clean_webserver clean_SnowTcpLib

clean_webserver:  clean_SnowTcpLib
	@rm -rf ./webserver
	@rm -rf ./webserver.sym
	@rm -rf build/.objs/webserver/linux/x86_64/debug/src/db.cc.o
	@rm -rf build/.objs/webserver/linux/x86_64/debug/src/WebService.cc.o
	@rm -rf build/.objs/webserver/linux/x86_64/debug/webServer/HttpConn.cc.o
	@rm -rf build/.objs/webserver/linux/x86_64/debug/webServer/webServer.cc.o
	@rm -rf build/.objs/webserver/linux/x86_64/debug/webServer/TimeWheel.cc.o

clean_SnowTcpLib: 
	@rm -rf ./libSnowTcpLib.so
	@rm -rf ./SnowTcpLib.sym
	@rm -rf build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/Buffer.cc.o
	@rm -rf build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/Channel.cc.o
	@rm -rf build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/EventLoopThread.cc.o
	@rm -rf build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/Socket.cc.o
	@rm -rf build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/DefaultPoller.cc.o
	@rm -rf build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/TimerQueue.cc.o
	@rm -rf build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/Poller.cc.o
	@rm -rf build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/CurrentThread.cc.o
	@rm -rf build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/TcpServer.cc.o
	@rm -rf build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/Timestamp.cc.o
	@rm -rf build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/Logger.cc.o
	@rm -rf build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/Acceptor.cc.o
	@rm -rf build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/EventLoopThreadPool.cc.o
	@rm -rf build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/TcpConnection.cc.o
	@rm -rf build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/EPollPoller.cc.o
	@rm -rf build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/EventLoop.cc.o
	@rm -rf build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/InetAddress.cc.o
	@rm -rf build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/Timer.cc.o
	@rm -rf build/.objs/SnowTcpLib/linux/x86_64/debug/SnowTcpLib/Thread.cc.o

